# version: '1.0.0'

services:
  postgres:
    image: postgres:16-alpine
    shm_size: 4g
    cpu_count: 4
    user: root
    volumes:
      - ./.pgdata/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nationPulseDB
      - PGDATA=/var/lib/postgresql/data/db-files/
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - nationPulseDB

networks:
  nationPulseDB:
